### ISSUE TITLE
Theme implementation overrides implementation pseudo-classes

### ISSUE THREAD

**Issue by don-p** [venasolutions/react-lazy-paginated-tree#18]
On the "Paginator" element, the element has a base style and hover style that uses the `:hover` pseudo-class.  I'd like to provide a `background-color` style for this element, and I can do this in the Theme object like this:

```
  paginatorStyle: {
    paddingTop: '3px',
    paddingBottom: '3px',
    backgroundColor: '#d9e7f3',
    color: '#106EBE'
  },
```

However, it appears that what the Theme implementation does is to add element-level styles to the elements, which will override any class styles.  As a result, adding the `background-color` property to the theme as above, will override the `background-color` property in the `:hover` pseudo-class.

You can see this happening in the screen shot below that I captured in the Paginator hover state:
![screen shot 2018-11-08 at 3 39 09 pm](https://user-images.githubusercontent.com/1581060/48226070-be17bd00-e36c-11e8-947a-865b39c5df07.png)

You can see that even though the element is in its hover state, the `:hover` style is being overridden by the element-level style.

Can you provide a working solution for how to either a) customize the Paginator base theme style while retaining the Paginator hover style, or b) how to customize a theme style for a pseudo-class like `:hover`?

Thanks.

**Comment by don-p** [comment]
I'd also suggest labeling each of the element components with a relevant `className` property, which would provide more flexibility with customizing styling.

**Comment by boweihan** [comment]
Good catch. ClassName theme properties have been added in 0.7.0.

**Comment by don-p** [comment]
> ClassName theme properties have been added in 0.7.0.

This isn't really what I was suggesting, or what's typically done in components.  Since you have provided a known, fixed component structure, you can associated known, fixed classnames with each component.

So for example you can have a component structure like this:

```
<List class="rlpt-tree">
  <Loading  class="rlpt-loading"/>
  <ListItem class="rlpt-listitem">
    <DepthPadding  class="rlpt-padding"/>
    <Expander  class="rlpt-expander"/>
    <Checkbox  class="rlpt-checkbox"/>
    <Body class="rlpt-body" />
  </ListItem>
  <Paginator  class="rlpt-paginator"/>
</List>
```

This is what I've typically seen in component libraries, so that in addition to the component-generated dynamic classnames like "MuiList-root-60 MuiList-padding-61", there are also known, fixed classnames that end-users can extend.

**Comment by don-p** [comment]
@boweihan 

Is there a solution to customizing the hover classes without overriding/breaking the default MUI hover?

**Comment by boweihan** [comment]
@don-p I added the className theme properties because it allows applications that are using modular css-in-js frameworks to apply classes without using global configurations or global css. I'll add actual library-scoped classes as defaults for these classNames to satisfy the case that you have suggested in addition to the current behaviour.

**Comment by don-p** [comment]
@boweihan

Thanks, that makes sense.

Is there a solution to customizing the hover classes without overriding/breaking the default MUI hover?
That was the primary/original issue here, in the initial comment.

**Comment by pilifs** [comment]
I think the only clean way to handle this for every case is to allow every component to be replaceable. Then you'll be able to do whatever you want. Hypothetically, if you could do that, the best option here would be overriding the way [Material UI recommends](https://material-ui.com/customization/overrides/), likely using their withStyles HOC. In my experience, it's a huge PITA to do anything with pure CSS and Material UI, so any other solution will likely be hacky and a one-off.

React Table does custom components well. See their [custom Cell component example](https://react-table.js.org/#/story/cell-renderers-custom-components). Each column object has an optional `Cell` property that gets called with cell data and can render whatever you want.

@boweihan If you're cool with this approach, let's make an issue for it. It may not be too much work to do now. There aren't a ton of different components, just need to separate the data from presentation.

@don-p In the short term, one other thing you may want to try is wrapping the Tree component with a custom [Material UI theme provider](https://material-ui.com/customization/themes/#theme-provider). If you don't have another one loaded on your page already then this might not be too bad.

**Comment by boweihan** [comment]
@pilifs each component in the tree hierarchy 

```
List: <React.Component />
ListItem: <React.Component />
Expander: <React.Component />
Checkbox: <React.Component />
Body: <React.Component />
Paginator: <React.Component />
Loading: <React.Component />
DepthPadding: <React.Component />
```

is already replaceable via props (the flow types for each component correspond to the props that are available via that component if you implement it custom). The default components are available as a convenience although the intent is for those to also be customizable via theme.

**Comment by pilifs** [comment]
Okay, after speaking with @boweihan this should be resolved shortly with two updates, sometime this week:

1) Make Material UI an external dependency with a Material UI theme using their recommended styling that replaces the currently defaultTheme.
2) Very simple default theme with optional CSS import that you can override as normal.

It's very difficult (not recommended) to override any Material UI component with standard CSS. This isn't a problem with the library necessarily, you'll have the same issue with any MUI app, aside from the fact that we are including it in the bundle and not exposing in any way.

**Comment by don-p** [comment]
@boweihan @pilifs 

I'm not sure what the discussion in the above two comments is about.

With addition of the option to add classnames to the individual component elements, this is easily solved as-is, and I've already done that.  I'm able to customize/override any class/styling that I need to.

I'm not sure what the need is to remove mui from the dependencies.  If you, as an npm package developer would like to follow mui styling, then it seems reasonable to include that as a dependency.  However, you should maintain the dependency with the latest mui version.

As a related side-note, I'd suggest providing default package-namespaced classnames, rather than null as you've provided in the default theme:

```
  bodyClassName: null,
  bodyTextClassName: null,
  checkboxClassName: null,
  expanderClassName: null,
  listClassName: null,
  listItemClassName: null,
  loadingClassName: null,
  loadingTextClassName: null,
  paginatorClassName: null,
  paginatorTextClassName: null,

```

**Comment by pilifs** [comment]
Closing this. It's a Material UI styling issue, not ours. Improved theming may help, but you have a couple of options before then:

1) Improved CSS specificity. Note that hover state is "specifically" mentioned in their docs, see the last two points here for suggestions: https://material-ui.com/customization/overrides/#overriding-with-classes
2) Pass your own component to Tree (if using MUI, preferably styled with JSS) to override the default Paginator: `<Tree Paginator={Whatever} ... />`

re: last reply, both have issues open. We're working on virtualization now. I'm not too familiar with Typescript (we use Flow internally), but this shouldn't be hard. Feel free to submit a PR for it. Thanks!
