### ISSUE TITLE
What is the purpose of dist/index.html?

### ISSUE THREAD

**Issue by pilifs** [venasolutions/react-lazy-paginated-tree#23]
Right now this file doesn't seem to do anything. It's a list of titles that also loads the bundle. Is it setup and in use anywhere? If not, are there any plans to do so? It would help with testing.

**Comment by boweihan** [comment]
@pilifs This file was originally used to test the tree but is not in use at the moment. I removed some dead code from it in version 0.7.1. The script to serve it with a built version of the tree is still available in package.json as `npm run start or npm start`.

It would be great to use it for manual/automated testing. Did you have something in mind?

**Comment by boweihan** [comment]
Closing this issue as dist/index.html has been removed for now.
